const baseTime = Date.UTC(2026, 3, 16, 4, 0, 0);

export const defaultProducts = [
  // --- QUANTUM SERIES LAPTOPS ---
  {
    _id: 'default-1',
    id: 'default-1',
    name: 'Yunax Horizon 15 Air',
    slug: 'yunax-horizon-15-air',
    category: 'Laptops',
    brand: 'Yunax',
    priceCents: 6299000,
    stock: 12,
    featured: true,
    description: 'Ultra-slim 15.6-inch professional laptop designed for the modern nomad. Features a brushed magnesium chassis and military-grade durability.',
    images: ['https://dlcdnwebimgs.asus.com/gain/ac75b6f3-379c-4507-b027-2a962cf9c9e7/w800'],
    highlights: ['Intel Horizon-Core i7', 'Vivid-Glass Anti-glare', '16GB LPDDR5 / 1TB SSD', '180-degree Lay-flat hinge'],
    specs: { brand: 'Yunax', series: 'Horizon Air', processor: 'Pro-Stream i7 Gen 12', graphics: 'Iris Vision Graphics', memory: '16GB Dual-Channel', storage: '1TB Ultra-Fast SSD', battery: 'Fast charge 60% in 45m' },
    createdAt: baseTime,
  },
  {
    _id: 'default-2',
    id: 'default-2',
    name: 'Yunax Combat G15 Pro',
    slug: 'yunax-combat-g15-pro',
    category: 'Laptops',
    brand: 'Yunax',
    priceCents: 9499000,
    stock: 8,
    description: 'Battle-hardened gaming machine with high-altitude cooling and a reinforced tactical chassis. Built for extreme conditions.',
    images: ['https://dlcdnwebimgs.asus.com/gain/3166c96d-5c61-4ae7-9d62-d272df1fe385/w800'],
    highlights: ['Combat-Spec Ryzen 7', 'Vision-RTX Graphics', '144Hz Tactical Display', 'Reinforced G-Chassis'],
    specs: { brand: 'Yunax', series: 'Combat G', model: 'G15-P', processor: 'Combat-7 7435HS', graphics: 'Vision-RTX 3050', memory: '16GB DDR5', storage: '1TB SSD', cooling: 'Dual-Fan Tactical System' },
    createdAt: baseTime - 1000,
  },
  {
    _id: 'default-3',
    id: 'default-3',
    name: 'Yunax StudioBook 15',
    slug: 'yunax-studiobook-15',
    category: 'Laptops',
    brand: 'Yunax',
    priceCents: 6799000,
    stock: 10,
    description: 'A masterpiece of design for creators. The StudioBook features a micro-edge color-accurate display and premium tactile keyboard.',
    images: ['https://hp.widen.net/content/filfkmawoq/webp/filfkmawoq.png?color=ffffff00&dpi=72&h=860&w=1146'],
    highlights: ['Creator-Grade Ryzen 5', 'Precision Color Display', 'Enhanced Creative Memory', '512GB Low-Latency Storage'],
    specs: { brand: 'Yunax', series: 'StudioBook', processor: 'Stream-Ready 4500U', graphics: 'Studio-Integrated Graphics', memory: '16GB High-Speed', storage: '512GB Ultra-NVMe', weight: '1.68 kg' },
    createdAt: baseTime - 2000,
  },
  {
    _id: 'default-4',
    id: 'default-4',
    name: 'HP Victus 15 Gaming',
    slug: 'hp-victus-15-gaming-laptop',
    category: 'Laptops',
    brand: 'HP',
    priceCents: 8999000,
    stock: 6,
    featured: true,
    description: 'A gaming PC that doesn\'t look like one. Powerful RTX graphics in a clean, professional design ready for work or play.',
    images: ['https://www.hp.com/content/dam/sites/omen/worldwide/laptops/2022-victus-15-intel/Hero%20Image%201.png'],
    highlights: ['Intel 13th Gen CPU', 'RTX 4050 Graphics', 'High-refresh screen', 'Omen thermal design'],
    specs: { brand: 'HP', model: '15-fa0000', processor: 'Core i5-13500H', graphics: 'RTX 4050', memory: '16GB DDR4', storage: '1TB NVMe', cooling: 'Dual-fan OMEN legacy' },
    createdAt: baseTime - 3000,
  },

  // --- ELITE PERIPHERALS ---
  {
    _id: 'default-5',
    id: 'default-5',
    name: 'Yunax Tactile Pro TKL',
    slug: 'yunax-tactile-pro-keyboard',
    category: 'Gaming Accessories',
    brand: 'Yunax',
    priceCents: 1899000,
    stock: 15,
    description: 'Precision mechanical engineering with proprietary magnetic switches. Zero latency for elite competitive play.',
    images: ['/products/new/keyboard_apex.png'],
    highlights: ['Yunax Magnetic Switches', 'Integrated Status OLED', 'Aeronautical Aluminum', 'Precision PBT keycaps'],
    specs: { switches: 'Yunax Omni-Magnetic', response: '0.1ms', actuation: 'Variable 0.2mm - 4.0mm', lighting: 'Aura-RGB Per-Key', software: 'Yunax Control Center' },
    createdAt: baseTime - 4000,
  },
  {
    _id: 'default-6',
    id: 'default-6',
    name: 'Yunax Swift-Wing Wireless',
    slug: 'yunax-swift-wing-mouse',
    category: 'Gaming Accessories',
    brand: 'Yunax',
    priceCents: 1299000,
    stock: 20,
    featured: true,
    description: 'The lightest competitive mouse in the Yunax lineup. Engineered for speed and surgical accuracy.',
    images: ['/products/new/mouse_viper.png'],
    highlights: ['30K Precision Sensor', 'Extremely Low 70g Weight', 'Infinite-Life Optical Clicks', 'Swift-Link Wireless Tech'],
    specs: { weight: '70g', sensor: 'Precision-30K', battery: '100+ Hours', buttons: '8 Fully Custom', acceleration: '50G Max' },
    createdAt: baseTime - 5000,
  },
  {
    _id: 'default-7',
    id: 'default-7',
    name: 'Nebula 7.1 RGB Headset',
    slug: 'nebula-rgb-headset',
    category: 'Gaming Accessories',
    brand: 'Yunax',
    priceCents: 549000,
    stock: 35,
    description: 'Immersive surround sound experience with memory foam earcups for marathon gaming sessions.',
    images: ['/products/gadgets.jpeg'],
    highlights: ['7.1 Surround Sound', 'Noise-cancelling Mic', 'Dynamic RGB Lighting', 'Universal Compatibility'],
    specs: { drivers: '53mm Neodymium', mics: 'Unidirection Noise-Cancelling', weight: '320g', cable: '2.2m Braided', connectivity: 'USB / 3.5mm' },
    createdAt: baseTime - 6000,
  },
  {
    _id: 'default-8',
    id: 'default-8',
    name: 'Titan G-Series Pro Chair',
    slug: 'titan-pro-gaming-chair',
    category: 'Gaming Accessories',
    brand: 'Yunax',
    priceCents: 2490000,
    stock: 5,
    description: 'Engineering excellence meets comfort. 4D armrests and magnetic lumbar support for the ultimate setup.',
    images: ['/products/gamiinglaptopandassecroies.jpeg'],
    highlights: ['4D Armrest adjustment', 'Magnetic Lumbar Pillow', '165-degree recline', 'Breathable PU Leather'],
    specs: { material: 'Premium PU Leather', base: 'Class 4 Gas Lift', load: '120kg', frame: 'Full Steel Structure', warranty: '3 Years' },
    createdAt: baseTime - 7000,
  },

  // --- LAPTOP ACCESSORIES ---
  {
    _id: 'default-9',
    id: 'default-9',
    name: 'HyperDrive 10-in-1 Hub',
    slug: 'hyperdrive-10-in-1-hub',
    category: 'Laptop Accessories',
    brand: 'Hyper',
    priceCents: 749000,
    stock: 40,
    description: 'Turn one USB-C port into a connectivity powerhouse with HDMI 4K, Gigabit Ethernet, and 100W PD.',
    images: ['/products/new/hub_hyperdrive.png'],
    highlights: ['4K HDMI Output', '100W Power Delivery', 'SD / MicroSD Slots', 'Gigabit Ethernet'],
    specs: { ports: '10 Ports', material: 'Brushed Aluminum', output: '4K @ 60Hz', pd: '100W Pass-through', size: 'Pocket Friendly' },
    createdAt: baseTime - 8000,
  },
  {
    _id: 'default-10',
    id: 'default-10',
    name: 'Arctic Multi-Fan Cooling Pad',
    slug: 'arctic-laptop-cooler',
    category: 'Laptop Accessories',
    brand: 'Yunax',
    priceCents: 229000,
    stock: 50,
    description: 'Prevent thermal throttling during intense work or gaming. Triple silent fans with adjustable speed.',
    images: ['/products/gamiinglaptopandassecroies.jpeg'],
    highlights: ['Triple 120mm Fans', 'Metal Mesh Top', 'Adjustable Height', 'Silent Operation'],
    specs: { fans: '3 x 1200 RPM', weight: '850g', adjustment: '5 Levels', power: 'USB Powered', lighting: 'Ice Blue LED' },
    createdAt: baseTime - 9000,
  },
  {
    _id: 'default-11',
    id: 'default-11',
    name: 'Shield Carbon Sleeve',
    slug: 'shield-carbon-laptop-sleeve',
    category: 'Laptop Accessories',
    brand: 'Yunax',
    priceCents: 149000,
    stock: 30,
    description: 'Weather-resistant protection with a modern carbon fiber texture. Fits laptops up to 16".',
    images: ['/products/mobileassceories.jpeg'],
    highlights: ['Waterproof exterior', 'Soft Microfiber lining', 'Extra Gear pocket', 'Shock-proof edges'],
    specs: { material: 'EVA + Carbon Fiber', size: 'Up to 16"', weight: '240g', closure: 'Weather-seal Zipper' },
    createdAt: baseTime - 10000,
  },

  // --- CPU ACCESSORIES ---
  {
    _id: 'default-12',
    id: 'default-12',
    name: 'Kraken Elite 360 LCD Cooler',
    slug: 'kraken-elite-360-aio',
    category: 'CPU Accessories',
    brand: 'NZXT',
    priceCents: 2499000,
    stock: 8,
    featured: true,
    description: 'The ultimate liquid cooler. Customizable 2.36" LCD display for system stats or your favorite GIFs.',
    images: ['/products/new/cooler_kraken.png'],
    highlights: ['640x640 LCD Screen', '360mm Radiator', 'Stat-driven monitoring', 'Quiet CAM-ready fans'],
    specs: { pump: '8th Gen Asetek', resolution: '640 x 640 px', fans: '3 x F120 RGB', socket: 'Intel / AMD Multi', warranty: '6 Years' },
    createdAt: baseTime - 11000,
  },
  {
    _id: 'default-13',
    id: 'default-13',
    name: 'Vortex ARGB Fan Pack (3)',
    slug: 'vortex-argb-fan-3-pack',
    category: 'CPU Accessories',
    brand: 'Yunax',
    priceCents: 399000,
    stock: 60,
    description: 'High static pressure fans with mesmerizing circular lighting effects. Controller included.',
    images: ['https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&q=80&w=800'],
    highlights: ['3 x 120mm Fans', 'Infinite Mirror Effect', 'Hydro-bearing silent', 'Sync with Motherboard'],
    specs: { rpm: '600 - 1800 RPM', airflow: '58 CFM', noise: '22 dBA', pins: '4-Pin PWM', control: 'Included HUB' },
    createdAt: baseTime - 12000,
  },

  // --- DESKTOP ---
  {
    _id: 'default-14',
    id: 'default-14',
    name: 'Zenith Pro Extreme PC',
    slug: 'yunax-zenith-pro-desktop',
    category: 'CPU Accessories',
    brand: 'Yunax',
    priceCents: 44999000,
    stock: 3,
    featured: true,
    description: 'Our most powerful build ever. Hand-assembled with the industry\'s best components for zero bottlenecks.',
    images: ['/products/new/desktop_zenith.png'],
    highlights: ['Core i9-14900K', 'RTX 4090 24GB', '64GB DDR5 RAM', 'Liquid Cooled GPU/CPU'],
    specs: { cpu: 'Intel i9-14900K', gpu: 'RTX 4090', ram: '64GB 6000MHz', psu: '1200W Titanium', case: 'Full Glass View' },
    createdAt: baseTime - 13000,
  },
  {
    _id: 'default-15',
    id: 'default-15',
    name: 'Studio Mini-PC Pro',
    slug: 'studio-mini-pc-pro',
    category: 'Desktop',
    brand: 'Yunax',
    priceCents: 7490000,
    stock: 12,
    description: 'Pro performance in an ultra-compact chassis. Perfect for designers and high-end office setups.',
    images: ['/products/editingsystem.jpeg'],
    highlights: ['Core i7 Processor', '32GB RAM', '2TB NVMe SSD', 'Supports 3 Monitors'],
    specs: { form: 'Ultra SFF', cpu: 'Intel i7-13700T', graphics: 'Intel UHD 770', connectivity: 'Thunderbolt 4', mount: 'VESA included' },
    createdAt: baseTime - 14000,
  },

  // --- DESKTOP ACCESSORIES ---
  {
    _id: 'default-16',
    id: 'default-16',
    name: 'Odyssey Neo G9 Monitor',
    slug: 'odyssey-neo-g9-monitor',
    category: 'Desktop Accessories',
    brand: 'Samsung',
    priceCents: 12499000,
    stock: 7,
    description: 'The world\'s most immersive gaming monitor. 49-inch curved masterpiece with 240Hz refresh rate.',
    images: ['/products/new/monitor_odyssey.png'],
    highlights: ['49" Curved Panel', 'Mini-LED Local Dimming', '240Hz / 1ms', 'Quantum HDR 2000'],
    specs: { res: '5120 x 1440', curve: '1000R', brightness: '2000 nits Peak', ports: 'HDMI 2.1 / DP 1.4', panel: 'Mini-LED' },
    createdAt: baseTime - 15000,
  },
  {
    _id: 'default-17',
    id: 'default-17',
    name: 'Studio Pro Streaming Mic',
    slug: 'studio-pro-microphone',
    category: 'Desktop Accessories',
    brand: 'Yunax',
    priceCents: 1290000,
    stock: 15,
    description: 'Broadcast-quality condenser microphone for streaming, podcasts, and pro voice-overs.',
    images: ['https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&q=80&w=800'],
    highlights: ['Studio Condenser capsule', 'Zero-latency monitoring', 'Built-in Pop Filter', 'USB-C Plug & Play'],
    specs: { pattern: 'Cardioid', frequency: '20Hz - 20kHz', bitDepth: '24-bit', rate: '96kHz', body: 'All-metal construction' },
    createdAt: baseTime - 16000,
  },
  {
    _id: 'default-18',
    id: 'default-18',
    name: 'Pro 4K HDR Webcam',
    slug: 'pro-4k-webcam',
    category: 'Desktop Accessories',
    brand: 'Yunax',
    priceCents: 849000,
    stock: 22,
    description: 'Crystal clear 4K video for your professional calls and high-end streaming setup.',
    images: ['https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=800'],
    highlights: ['True 4K 30fps Video', 'Deep AI Autofocus', 'HDR Contrast Balance', 'Dual Stereo Mics'],
    specs: { resolution: '3840 x 2160', fov: '90-degree wide', shutter: 'Physical Privacy', mic: 'Noise-cancelling', base: 'Tripod Ready' },
    createdAt: baseTime - 17000,
  },
  {
    _id: 'default-19',
    id: 'default-19',
    name: 'Hi-Fi Elite Speakers',
    slug: 'hifi-bookshelf-speakers',
    category: 'Desktop Accessories',
    brand: 'Yunax',
    priceCents: 1890000,
    stock: 10,
    description: 'Reference-grade bookshelf speakers for audiophiles. Natural wood finish with modern drivers.',
    images: ['https://images.unsplash.com/photo-1623150531061-00109968832a?auto=format&fit=crop&q=80&w=800'],
    highlights: ['Active Bookshelf design', 'Bluetooth 5.0 AptX', 'Aramid Fiber Woofers', 'Optical / RCA Input'],
    specs: { power: '60W RMS', tweeters: '1" Silk Dome', woofers: '4" Glass Fiber', remote: 'Wireless included', finish: 'Sleek Walnut' },
    createdAt: baseTime - 18000,
  },
];

export const getDefaultProducts = () => defaultProducts.map((product) => ({
  ...product,
  images: [...product.images],
  highlights: [...product.highlights],
  specs: { ...product.specs },
}));

export const findDefaultProductBySlug = (slug) =>
  getDefaultProducts().find((product) => product.slug === slug) || null;
